### PR TITLE
Fix usage of `(fn (mut this.something) someValue)`.

### LINKED ISSUE #6: Not working correctly with `mut`
I'm using the `fn` helper as below to handle events on an input:

```
<input
  type="text"
  value={{@band.name}}
  {{on "blur" (fn (mut showErrors.name) true)}}
  {{on "input" (fn this.updateName @band)}}
>
```

The `input` handler works perfectly but I get the following error for the `blur` one:

> Assertion Failed: You must pass a function as the `fn` helpers first argument, you passed false

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes #6.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -17,6 +17,30 @@ module.exports = {
...
+        params: {},
+      };
+
+      registry.add('htmlbars-ast-plugin', pluginObj);
+    }
+  },
+
+  _buildPlugin() {
+    return {
+      name: 'component-attributes',
```
Comment (lifeart) [inline index.js:36]: lol, sorry for late comment, looks like this name should be different

Comment (rwjblue) [reply index.js:36]: hahahaahahah, 😭

Comment (lifeart) [reply index.js:36]: @rwjblue I'm wondering is any case to use `mut` without combination with `fn`?
like `<MyComponent @onChange={{mut this.content}} />`, `{{my-component onChange=(mut this.content}}` ? If it's valid case - looks like current transform not cover it

Comment (rwjblue) [reply index.js:36]: This polyfill is **only** for `fn` so I'm not sure it matters what you'd use `{{mut` for if it isn't with `fn` from this libraries perspective.

Also, I'm not sure why you would do `<MyComponent @onChange={{mut this.content}} />`, what is the point of that `mut` invocation from your perspective?

Comment (lifeart) [reply index.js:36]: `<MyComponent @onChange={{mut this.content}} />` looks pretty interesting from declarative side, mut result assept only one argument, so, onChange must be invoked with only one argument, it's pretty clear.

in case of `{{fn @someExternal}}` we can't imagine how arguments already binded to this function.

`mut` - pretty clear way to get atomic component context properties mutation

Comment (rwjblue) [reply index.js:36]: I think you may be misunderstanding how `{{mut` works, in that position with those arguments `{{mut` does **not** give you a function at all. It gives you the literal value that was in `this.content`. 

`{{mut` only emits a function like thing when passed to "special" helpers (mostly `action`), which uses some private internal details in order to make it work. 

I made a small mockup to show what I mean: https://codesandbox.io/s/my-app-fjvgh

Comment (lifeart) [reply index.js:36]: is `mut` produce kinda `mutableReference` with `update()` method using with `action`? 
https://github.com/emberjs/ember.js/blob/c21c417705d90837da898059faf93741fa564334/packages/%40ember/-internals/glimmer/lib/helpers/mut.ts

And in end-user-cases it available as  "value" and sometimes as "reference"?

Comment (rwjblue) [reply index.js:36]: Ya, roughly but the reference itself is never exposed to userland (that’s why the fix I had to do in this PR was to wrap in action). 

I personally think the thing you were suggesting that mut return a `{ value, update(){} }` kinda thing would make `mut` **actually** useful and we should consider trying to make a path to that.

Also, FWIW, this roughly equates to the thing I was mentioning around 16:00 in this video https://youtu.be/c0Rl6o9wLX0. 😃

Comment (lifeart) [reply index.js:36]: Un user-space we able to get `mutable`  as https://ember-twiddle.com/0575c8ca83be668eb694811cd7adb14f?openFiles=templates.components.my-component.hbs%2C
